<?php

namespace OmSdk\Modules\Campaign\Repositories\Eloquent;

use Common\Repositories\Eloquent\AbstractEloquentRepository;
use OmSdk\Modules\Campaign\Models\CampaignPayment;
use OmSdk\Modules\Campaign\Repositories\Contracts\ICampaignPaymentRepository;

/**
 * Class CampaignPaymentRepository
 * @package OmSdk\Modules\Campaign\Repositories\Eloquent
 */
class CampaignPaymentRepository extends AbstractEloquentRepository implements ICampaignPaymentRepository
{
    /**
     * Map model
     * @return string
     */
    protected function _getModel()
    {
        return CampaignPayment::class;
    }

    /**
     * Set query filter
     * @param mixed $query
     * @param array $attributes
     * @return void
     */
    public function filter($query, $attributes = [])
    {
        
    }

    protected function _prepareConditions($conditions, $query)
    {
        $query = parent::_prepareConditions($conditions, $query); // TODO: Change the autogenerated stub

        if (isset($conditions['payment_id'])){
            $payment_id = $conditions['payment_id'];

            $query->where('payment_account_id', $payment_id);
        }

        if (isset($conditions['campaign_id'])){
            $campaign_id = $conditions['campaign_id'];

            $query->where('campaign_id', $campaign_id);
        }

        return $query;
    }
}