<?php

namespace OmSdk\Modules\Payment\Repositories\Eloquent;

use Common\Repositories\Eloquent\AbstractEloquentRepository;
use OmSdk\Modules\Payment\Models\PaymentAccountAssignee;
use OmSdk\Modules\Payment\Repositories\Contracts\IPaymentAccountAssigneeRepository;

class PaymentAccountAssigneeRepository extends AbstractEloquentRepository implements IPaymentAccountAssigneeRepository
{

    protected function _getModel()
    {
        return PaymentAccountAssignee::class;
    }

    /**
     * @param $conditions
     * @param $query
     * @return mixed
     */
    public function _prepareConditions($conditions, $query)
    {
        return parent::_prepareConditions($conditions, $query); // TODO: Change the autogenerated stub
    }

    /**
     * @param $fetchOptions
     * @param $query
     * @return mixed
     */
    public function _prepareFetchOptions($fetchOptions, $query)
    {
        return parent::_prepareFetchOptions($fetchOptions, $query); // TODO: Change the autogenerated stub
    }
}