<?php

namespace OmSdk\Modules\Customer\Repositories\Eloquent;

use Common\Repositories\Eloquent\AbstractEloquentRepository;
use OmSdk\Modules\Customer\Models\CustomerMission;
use OmSdk\Modules\Customer\Repositories\Contracts\ICustomerMissionRepository;

class CustomerMissionRepository extends AbstractEloquentRepository implements ICustomerMissionRepository
{
    /**
     * @return string
     */
    protected function _getModel()
    {
        return CustomerMission::class;
    }

    /**
     * @param $conditions
     * @param $query
     * @return mixed
     */
    public function _prepareConditions($conditions, $query)
    {
        return parent::_prepareConditions($conditions, $query); // TODO: Change the autogenerated stub
    }

    /**
     * @param $fetchOptions
     * @param $query
     * @return mixed
     */
    public function _prepareFetchOptions($fetchOptions, $query)
    {
        return parent::_prepareFetchOptions($fetchOptions, $query); // TODO: Change the autogenerated stub
    }
}